### PR TITLE
Forgot to commit the command's data.

### PR DESCRIPTION
**Pull request by DDR-Khat**
You'll need this for the team stuff to work.

### CODE REVIEW

**Comment by waidesoper** [comment]
Building it now. This is probably worth a version increment.

There's a few bugs we need to fix from the_vault-public too. I did a PR for one last night. Bonne has also submitted a bunch of PRs that we might need to review and pull into this codebase

**Comment by DDR-Khat** [comment]
I'm personally gonna hold off version bumping until the timer issue can be resolved. But this here is your repo so your choice.

**Comment by waidesoper** [comment]
2 questions: What happens when a player bails out of a coop raid? What should happen?

**Comment by DDR-Khat** [comment]
1. When a person exists the raid, it currently fetches all players still in the dimension and pulls them out with that player.

2. This is subjective in the case of co-operative vaults; you either.
- 1. Leave it as-is, allowing there to be a 'safety' player standing near the portal to help everyone escape.
- 2. Let that player leave, and the timer continue for everyone else.
- 3. Let that player leave, setting the timer to 20 seconds remaining (akin to a boss defeat) when that player does; This encourages the team to work together to exit and not have a "freebie" exit.
- 4. Configurationable options of the above.

**Pull request merged**
